// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: pb/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamInfo_Status int32

const (
	StreamInfo_ACTIVE StreamInfo_Status = 0
	StreamInfo_STOP   StreamInfo_Status = 1
)

// Enum value maps for StreamInfo_Status.
var (
	StreamInfo_Status_name = map[int32]string{
		0: "ACTIVE",
		1: "STOP",
	}
	StreamInfo_Status_value = map[string]int32{
		"ACTIVE": 0,
		"STOP":   1,
	}
)

func (x StreamInfo_Status) Enum() *StreamInfo_Status {
	p := new(StreamInfo_Status)
	*p = x
	return p
}

func (x StreamInfo_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamInfo_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_message_proto_enumTypes[0].Descriptor()
}

func (StreamInfo_Status) Type() protoreflect.EnumType {
	return &file_pb_message_proto_enumTypes[0]
}

func (x StreamInfo_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamInfo_Status.Descriptor instead.
func (StreamInfo_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{4, 0}
}

type StreamInfoResponse_Answer int32

const (
	StreamInfoResponse_ENTER StreamInfoResponse_Answer = 0
	StreamInfoResponse_LEAVE StreamInfoResponse_Answer = 1
)

// Enum value maps for StreamInfoResponse_Answer.
var (
	StreamInfoResponse_Answer_name = map[int32]string{
		0: "ENTER",
		1: "LEAVE",
	}
	StreamInfoResponse_Answer_value = map[string]int32{
		"ENTER": 0,
		"LEAVE": 1,
	}
)

func (x StreamInfoResponse_Answer) Enum() *StreamInfoResponse_Answer {
	p := new(StreamInfoResponse_Answer)
	*p = x
	return p
}

func (x StreamInfoResponse_Answer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamInfoResponse_Answer) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_message_proto_enumTypes[1].Descriptor()
}

func (StreamInfoResponse_Answer) Type() protoreflect.EnumType {
	return &file_pb_message_proto_enumTypes[1]
}

func (x StreamInfoResponse_Answer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamInfoResponse_Answer.Descriptor instead.
func (StreamInfoResponse_Answer) EnumDescriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{5, 0}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pb_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pb_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{1}
}

type Static struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PrevMessageId string                 `protobuf:"bytes,2,opt,name=prev_message_id,json=prevMessageId,proto3" json:"prev_message_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Static) Reset() {
	*x = Static{}
	mi := &file_pb_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Static) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Static) ProtoMessage() {}

func (x *Static) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Static.ProtoReflect.Descriptor instead.
func (*Static) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{2}
}

func (x *Static) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Static) GetPrevMessageId() string {
	if x != nil {
		return x.PrevMessageId
	}
	return ""
}

func (x *Static) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Static) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Static) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Static) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StaticResendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticResendRequest) Reset() {
	*x = StaticResendRequest{}
	mi := &file_pb_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticResendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticResendRequest) ProtoMessage() {}

func (x *StaticResendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticResendRequest.ProtoReflect.Descriptor instead.
func (*StaticResendRequest) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{3}
}

func (x *StaticResendRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StaticResendRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StreamInfo_Status      `protobuf:"varint,1,opt,name=status,proto3,enum=pb.StreamInfo_Status" json:"status,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_pb_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{4}
}

func (x *StreamInfo) GetStatus() StreamInfo_Status {
	if x != nil {
		return x.Status
	}
	return StreamInfo_ACTIVE
}

func (x *StreamInfo) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type StreamInfoResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Answer        StreamInfoResponse_Answer `protobuf:"varint,1,opt,name=answer,proto3,enum=pb.StreamInfoResponse_Answer" json:"answer,omitempty"`
	ChatId        string                    `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfoResponse) Reset() {
	*x = StreamInfoResponse{}
	mi := &file_pb_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoResponse) ProtoMessage() {}

func (x *StreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoResponse.ProtoReflect.Descriptor instead.
func (*StreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{5}
}

func (x *StreamInfoResponse) GetAnswer() StreamInfoResponse_Answer {
	if x != nil {
		return x.Answer
	}
	return StreamInfoResponse_ENTER
}

func (x *StreamInfoResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInit        bool                   `protobuf:"varint,1,opt,name=is_init,json=isInit,proto3" json:"is_init,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SeqNumber     uint32                 `protobuf:"varint,3,opt,name=seq_number,json=seqNumber,proto3" json:"seq_number,omitempty"`
	Offset        []byte                 `protobuf:"bytes,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_pb_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{6}
}

func (x *StreamChunk) GetIsInit() bool {
	if x != nil {
		return x.IsInit
	}
	return false
}

func (x *StreamChunk) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StreamChunk) GetSeqNumber() uint32 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

func (x *StreamChunk) GetOffset() []byte {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *StreamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*DataPacket_Static
	//	*DataPacket_ResendStatic
	//	*DataPacket_StreamInfo
	//	*DataPacket_StreamInfoResponse
	//	*DataPacket_StreamChunk
	//	*DataPacket_Ping
	//	*DataPacket_Pong
	Msg           isDataPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPacket) Reset() {
	*x = DataPacket{}
	mi := &file_pb_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPacket) ProtoMessage() {}

func (x *DataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPacket.ProtoReflect.Descriptor instead.
func (*DataPacket) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{7}
}

func (x *DataPacket) GetMsg() isDataPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DataPacket) GetStatic() *Static {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_Static); ok {
			return x.Static
		}
	}
	return nil
}

func (x *DataPacket) GetResendStatic() *StaticResendRequest {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_ResendStatic); ok {
			return x.ResendStatic
		}
	}
	return nil
}

func (x *DataPacket) GetStreamInfo() *StreamInfo {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_StreamInfo); ok {
			return x.StreamInfo
		}
	}
	return nil
}

func (x *DataPacket) GetStreamInfoResponse() *StreamInfoResponse {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_StreamInfoResponse); ok {
			return x.StreamInfoResponse
		}
	}
	return nil
}

func (x *DataPacket) GetStreamChunk() *StreamChunk {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_StreamChunk); ok {
			return x.StreamChunk
		}
	}
	return nil
}

func (x *DataPacket) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *DataPacket) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isDataPacket_Msg interface {
	isDataPacket_Msg()
}

type DataPacket_Static struct {
	Static *Static `protobuf:"bytes,1,opt,name=static,proto3,oneof"`
}

type DataPacket_ResendStatic struct {
	ResendStatic *StaticResendRequest `protobuf:"bytes,2,opt,name=resend_static,json=resendStatic,proto3,oneof"`
}

type DataPacket_StreamInfo struct {
	StreamInfo *StreamInfo `protobuf:"bytes,3,opt,name=stream_info,json=streamInfo,proto3,oneof"`
}

type DataPacket_StreamInfoResponse struct {
	StreamInfoResponse *StreamInfoResponse `protobuf:"bytes,4,opt,name=stream_info_response,json=streamInfoResponse,proto3,oneof"`
}

type DataPacket_StreamChunk struct {
	StreamChunk *StreamChunk `protobuf:"bytes,5,opt,name=stream_chunk,json=streamChunk,proto3,oneof"`
}

type DataPacket_Ping struct {
	Ping *Ping `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

type DataPacket_Pong struct {
	Pong *Pong `protobuf:"bytes,7,opt,name=pong,proto3,oneof"`
}

func (*DataPacket_Static) isDataPacket_Msg() {}

func (*DataPacket_ResendStatic) isDataPacket_Msg() {}

func (*DataPacket_StreamInfo) isDataPacket_Msg() {}

func (*DataPacket_StreamInfoResponse) isDataPacket_Msg() {}

func (*DataPacket_StreamChunk) isDataPacket_Msg() {}

func (*DataPacket_Ping) isDataPacket_Msg() {}

func (*DataPacket_Pong) isDataPacket_Msg() {}

var File_pb_message_proto protoreflect.FileDescriptor

const file_pb_message_proto_rawDesc = "" +
	"\n" +
	"\x10pb/message.proto\x12\x02pb\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"\xb5\x01\n" +
	"\x06Static\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12&\n" +
	"\x0fprev_message_id\x18\x02 \x01(\tR\rprevMessageId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x1a\n" +
	"\bmimeType\x18\x04 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"M\n" +
	"\x13StaticResendRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"t\n" +
	"\n" +
	"StreamInfo\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.pb.StreamInfo.StatusR\x06status\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\"\x1e\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\"\x84\x01\n" +
	"\x12StreamInfoResponse\x125\n" +
	"\x06answer\x18\x01 \x01(\x0e2\x1d.pb.StreamInfoResponse.AnswerR\x06answer\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\"\x1e\n" +
	"\x06Answer\x12\t\n" +
	"\x05ENTER\x10\x00\x12\t\n" +
	"\x05LEAVE\x10\x01\"\x8a\x01\n" +
	"\vStreamChunk\x12\x17\n" +
	"\ais_init\x18\x01 \x01(\bR\x06isInit\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"seq_number\x18\x03 \x01(\rR\tseqNumber\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\fR\x06offset\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"\xee\x02\n" +
	"\n" +
	"DataPacket\x12$\n" +
	"\x06static\x18\x01 \x01(\v2\n" +
	".pb.StaticH\x00R\x06static\x12>\n" +
	"\rresend_static\x18\x02 \x01(\v2\x17.pb.StaticResendRequestH\x00R\fresendStatic\x121\n" +
	"\vstream_info\x18\x03 \x01(\v2\x0e.pb.StreamInfoH\x00R\n" +
	"streamInfo\x12J\n" +
	"\x14stream_info_response\x18\x04 \x01(\v2\x16.pb.StreamInfoResponseH\x00R\x12streamInfoResponse\x124\n" +
	"\fstream_chunk\x18\x05 \x01(\v2\x0f.pb.StreamChunkH\x00R\vstreamChunk\x12\x1e\n" +
	"\x04ping\x18\x06 \x01(\v2\b.pb.PingH\x00R\x04ping\x12\x1e\n" +
	"\x04pong\x18\a \x01(\v2\b.pb.PongH\x00R\x04pongB\x05\n" +
	"\x03msgB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_message_proto_rawDescOnce sync.Once
	file_pb_message_proto_rawDescData []byte
)

func file_pb_message_proto_rawDescGZIP() []byte {
	file_pb_message_proto_rawDescOnce.Do(func() {
		file_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_message_proto_rawDesc), len(file_pb_message_proto_rawDesc)))
	})
	return file_pb_message_proto_rawDescData
}

var file_pb_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_message_proto_goTypes = []any{
	(StreamInfo_Status)(0),         // 0: pb.StreamInfo.Status
	(StreamInfoResponse_Answer)(0), // 1: pb.StreamInfoResponse.Answer
	(*Ping)(nil),                   // 2: pb.Ping
	(*Pong)(nil),                   // 3: pb.Pong
	(*Static)(nil),                 // 4: pb.Static
	(*StaticResendRequest)(nil),    // 5: pb.StaticResendRequest
	(*StreamInfo)(nil),             // 6: pb.StreamInfo
	(*StreamInfoResponse)(nil),     // 7: pb.StreamInfoResponse
	(*StreamChunk)(nil),            // 8: pb.StreamChunk
	(*DataPacket)(nil),             // 9: pb.DataPacket
}
var file_pb_message_proto_depIdxs = []int32{
	0, // 0: pb.StreamInfo.status:type_name -> pb.StreamInfo.Status
	1, // 1: pb.StreamInfoResponse.answer:type_name -> pb.StreamInfoResponse.Answer
	4, // 2: pb.DataPacket.static:type_name -> pb.Static
	5, // 3: pb.DataPacket.resend_static:type_name -> pb.StaticResendRequest
	6, // 4: pb.DataPacket.stream_info:type_name -> pb.StreamInfo
	7, // 5: pb.DataPacket.stream_info_response:type_name -> pb.StreamInfoResponse
	8, // 6: pb.DataPacket.stream_chunk:type_name -> pb.StreamChunk
	2, // 7: pb.DataPacket.ping:type_name -> pb.Ping
	3, // 8: pb.DataPacket.pong:type_name -> pb.Pong
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pb_message_proto_init() }
func file_pb_message_proto_init() {
	if File_pb_message_proto != nil {
		return
	}
	file_pb_message_proto_msgTypes[7].OneofWrappers = []any{
		(*DataPacket_Static)(nil),
		(*DataPacket_ResendStatic)(nil),
		(*DataPacket_StreamInfo)(nil),
		(*DataPacket_StreamInfoResponse)(nil),
		(*DataPacket_StreamChunk)(nil),
		(*DataPacket_Ping)(nil),
		(*DataPacket_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_message_proto_rawDesc), len(file_pb_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_message_proto_goTypes,
		DependencyIndexes: file_pb_message_proto_depIdxs,
		EnumInfos:         file_pb_message_proto_enumTypes,
		MessageInfos:      file_pb_message_proto_msgTypes,
	}.Build()
	File_pb_message_proto = out.File
	file_pb_message_proto_goTypes = nil
	file_pb_message_proto_depIdxs = nil
}
