// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: pb/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamControl_Action int32

const (
	StreamControl_START  StreamControl_Action = 0
	StreamControl_STOP   StreamControl_Action = 1
	StreamControl_RESUME StreamControl_Action = 2
)

// Enum value maps for StreamControl_Action.
var (
	StreamControl_Action_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "RESUME",
	}
	StreamControl_Action_value = map[string]int32{
		"START":  0,
		"STOP":   1,
		"RESUME": 2,
	}
)

func (x StreamControl_Action) Enum() *StreamControl_Action {
	p := new(StreamControl_Action)
	*p = x
	return p
}

func (x StreamControl_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamControl_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_message_proto_enumTypes[0].Descriptor()
}

func (StreamControl_Action) Type() protoreflect.EnumType {
	return &file_pb_message_proto_enumTypes[0]
}

func (x StreamControl_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamControl_Action.Descriptor instead.
func (StreamControl_Action) EnumDescriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{4, 0}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pb_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pb_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{1}
}

type Static struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint32                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Static) Reset() {
	*x = Static{}
	mi := &file_pb_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Static) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Static) ProtoMessage() {}

func (x *Static) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Static.ProtoReflect.Descriptor instead.
func (*Static) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{2}
}

func (x *Static) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Static) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Static) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StaticResendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint32                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticResendRequest) Reset() {
	*x = StaticResendRequest{}
	mi := &file_pb_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticResendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticResendRequest) ProtoMessage() {}

func (x *StaticResendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticResendRequest.ProtoReflect.Descriptor instead.
func (*StaticResendRequest) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{3}
}

func (x *StaticResendRequest) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type StreamControl struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MimeType        string                 `protobuf:"bytes,2,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Action          StreamControl_Action   `protobuf:"varint,3,opt,name=action,proto3,enum=pb.StreamControl_Action" json:"action,omitempty"`
	Offset          []byte                 `protobuf:"bytes,4,opt,name=offset,proto3" json:"offset,omitempty"`
	InitMetadata    []byte                 `protobuf:"bytes,5,opt,name=init_metadata,json=initMetadata,proto3" json:"init_metadata,omitempty"`
	LastReceivedSeq uint32                 `protobuf:"varint,6,opt,name=last_received_seq,json=lastReceivedSeq,proto3" json:"last_received_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamControl) Reset() {
	*x = StreamControl{}
	mi := &file_pb_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControl) ProtoMessage() {}

func (x *StreamControl) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControl.ProtoReflect.Descriptor instead.
func (*StreamControl) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{4}
}

func (x *StreamControl) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StreamControl) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *StreamControl) GetAction() StreamControl_Action {
	if x != nil {
		return x.Action
	}
	return StreamControl_START
}

func (x *StreamControl) GetOffset() []byte {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *StreamControl) GetInitMetadata() []byte {
	if x != nil {
		return x.InitMetadata
	}
	return nil
}

func (x *StreamControl) GetLastReceivedSeq() uint32 {
	if x != nil {
		return x.LastReceivedSeq
	}
	return 0
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SeqNumber     uint32                 `protobuf:"varint,2,opt,name=seq_number,json=seqNumber,proto3" json:"seq_number,omitempty"`
	Offset        []byte                 `protobuf:"bytes,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_pb_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{5}
}

func (x *StreamChunk) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StreamChunk) GetSeqNumber() uint32 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

func (x *StreamChunk) GetOffset() []byte {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *StreamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamResendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SqeNumber     uint32                 `protobuf:"varint,2,opt,name=sqe_number,json=sqeNumber,proto3" json:"sqe_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResendRequest) Reset() {
	*x = StreamResendRequest{}
	mi := &file_pb_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResendRequest) ProtoMessage() {}

func (x *StreamResendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResendRequest.ProtoReflect.Descriptor instead.
func (*StreamResendRequest) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{6}
}

func (x *StreamResendRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StreamResendRequest) GetSqeNumber() uint32 {
	if x != nil {
		return x.SqeNumber
	}
	return 0
}

type DataPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*DataPacket_Static
	//	*DataPacket_ResendStatic
	//	*DataPacket_Control
	//	*DataPacket_Chunk
	//	*DataPacket_ResendStream
	Msg           isDataPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPacket) Reset() {
	*x = DataPacket{}
	mi := &file_pb_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPacket) ProtoMessage() {}

func (x *DataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pb_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPacket.ProtoReflect.Descriptor instead.
func (*DataPacket) Descriptor() ([]byte, []int) {
	return file_pb_message_proto_rawDescGZIP(), []int{7}
}

func (x *DataPacket) GetMsg() isDataPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DataPacket) GetStatic() *Static {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_Static); ok {
			return x.Static
		}
	}
	return nil
}

func (x *DataPacket) GetResendStatic() *StaticResendRequest {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_ResendStatic); ok {
			return x.ResendStatic
		}
	}
	return nil
}

func (x *DataPacket) GetControl() *StreamControl {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *DataPacket) GetChunk() *StreamChunk {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DataPacket) GetResendStream() *StaticResendRequest {
	if x != nil {
		if x, ok := x.Msg.(*DataPacket_ResendStream); ok {
			return x.ResendStream
		}
	}
	return nil
}

type isDataPacket_Msg interface {
	isDataPacket_Msg()
}

type DataPacket_Static struct {
	Static *Static `protobuf:"bytes,1,opt,name=static,proto3,oneof"`
}

type DataPacket_ResendStatic struct {
	ResendStatic *StaticResendRequest `protobuf:"bytes,2,opt,name=resend_static,json=resendStatic,proto3,oneof"`
}

type DataPacket_Control struct {
	Control *StreamControl `protobuf:"bytes,3,opt,name=control,proto3,oneof"`
}

type DataPacket_Chunk struct {
	Chunk *StreamChunk `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"`
}

type DataPacket_ResendStream struct {
	ResendStream *StaticResendRequest `protobuf:"bytes,5,opt,name=resend_stream,json=resendStream,proto3,oneof"`
}

func (*DataPacket_Static) isDataPacket_Msg() {}

func (*DataPacket_ResendStatic) isDataPacket_Msg() {}

func (*DataPacket_Control) isDataPacket_Msg() {}

func (*DataPacket_Chunk) isDataPacket_Msg() {}

func (*DataPacket_ResendStream) isDataPacket_Msg() {}

var File_pb_message_proto protoreflect.FileDescriptor

const file_pb_message_proto_rawDesc = "" +
	"\n" +
	"\x10pb/message.proto\x12\x02pb\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"W\n" +
	"\x06Static\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\x12\x1a\n" +
	"\bmimeType\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"4\n" +
	"\x13StaticResendRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\"\x90\x02\n" +
	"\rStreamControl\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12\x1a\n" +
	"\bmimeType\x18\x02 \x01(\tR\bmimeType\x120\n" +
	"\x06action\x18\x03 \x01(\x0e2\x18.pb.StreamControl.ActionR\x06action\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\fR\x06offset\x12#\n" +
	"\rinit_metadata\x18\x05 \x01(\fR\finitMetadata\x12*\n" +
	"\x11last_received_seq\x18\x06 \x01(\rR\x0flastReceivedSeq\")\n" +
	"\x06Action\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x02\"w\n" +
	"\vStreamChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12\x1d\n" +
	"\n" +
	"seq_number\x18\x02 \x01(\rR\tseqNumber\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\fR\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"S\n" +
	"\x13StreamResendRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12\x1d\n" +
	"\n" +
	"sqe_number\x18\x02 \x01(\rR\tsqeNumber\"\x91\x02\n" +
	"\n" +
	"DataPacket\x12$\n" +
	"\x06static\x18\x01 \x01(\v2\n" +
	".pb.StaticH\x00R\x06static\x12>\n" +
	"\rresend_static\x18\x02 \x01(\v2\x17.pb.StaticResendRequestH\x00R\fresendStatic\x12-\n" +
	"\acontrol\x18\x03 \x01(\v2\x11.pb.StreamControlH\x00R\acontrol\x12'\n" +
	"\x05chunk\x18\x04 \x01(\v2\x0f.pb.StreamChunkH\x00R\x05chunk\x12>\n" +
	"\rresend_stream\x18\x05 \x01(\v2\x17.pb.StaticResendRequestH\x00R\fresendStreamB\x05\n" +
	"\x03msgB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_message_proto_rawDescOnce sync.Once
	file_pb_message_proto_rawDescData []byte
)

func file_pb_message_proto_rawDescGZIP() []byte {
	file_pb_message_proto_rawDescOnce.Do(func() {
		file_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_message_proto_rawDesc), len(file_pb_message_proto_rawDesc)))
	})
	return file_pb_message_proto_rawDescData
}

var file_pb_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_message_proto_goTypes = []any{
	(StreamControl_Action)(0),   // 0: pb.StreamControl.Action
	(*Ping)(nil),                // 1: pb.Ping
	(*Pong)(nil),                // 2: pb.Pong
	(*Static)(nil),              // 3: pb.Static
	(*StaticResendRequest)(nil), // 4: pb.StaticResendRequest
	(*StreamControl)(nil),       // 5: pb.StreamControl
	(*StreamChunk)(nil),         // 6: pb.StreamChunk
	(*StreamResendRequest)(nil), // 7: pb.StreamResendRequest
	(*DataPacket)(nil),          // 8: pb.DataPacket
}
var file_pb_message_proto_depIdxs = []int32{
	0, // 0: pb.StreamControl.action:type_name -> pb.StreamControl.Action
	3, // 1: pb.DataPacket.static:type_name -> pb.Static
	4, // 2: pb.DataPacket.resend_static:type_name -> pb.StaticResendRequest
	5, // 3: pb.DataPacket.control:type_name -> pb.StreamControl
	6, // 4: pb.DataPacket.chunk:type_name -> pb.StreamChunk
	4, // 5: pb.DataPacket.resend_stream:type_name -> pb.StaticResendRequest
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_message_proto_init() }
func file_pb_message_proto_init() {
	if File_pb_message_proto != nil {
		return
	}
	file_pb_message_proto_msgTypes[7].OneofWrappers = []any{
		(*DataPacket_Static)(nil),
		(*DataPacket_ResendStatic)(nil),
		(*DataPacket_Control)(nil),
		(*DataPacket_Chunk)(nil),
		(*DataPacket_ResendStream)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_message_proto_rawDesc), len(file_pb_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_message_proto_goTypes,
		DependencyIndexes: file_pb_message_proto_depIdxs,
		EnumInfos:         file_pb_message_proto_enumTypes,
		MessageInfos:      file_pb_message_proto_msgTypes,
	}.Build()
	File_pb_message_proto = out.File
	file_pb_message_proto_goTypes = nil
	file_pb_message_proto_depIdxs = nil
}
